const stations = {
  'anyang': {
    label: 'China Station 01',
    title: 'Anyang',
    images: [
      'assets/research/zidao/photos/anyang/anyang-001.jpg',
      'assets/research/zidao/photos/anyang/anyang-002.jpg',
      'assets/research/zidao/photos/anyang/anyang-003.jpg',
      'assets/research/zidao/photos/anyang/anyang-004.jpg',
      'assets/research/zidao/photos/anyang/anyang-005.jpg',
      'assets/research/zidao/photos/anyang/anyang-006.jpg',
      'assets/research/zidao/photos/anyang/anyang-007.jpg',
      'assets/research/zidao/photos/anyang/anyang-008.jpg',
      'assets/research/zidao/photos/anyang/anyang-009.jpg',
      'assets/research/zidao/photos/anyang/anyang-010.jpg',
      'assets/research/zidao/photos/anyang/anyang-011.jpg',
      'assets/research/zidao/photos/anyang/anyang-012.jpg',
      'assets/research/zidao/photos/anyang/anyang-013.jpg',
      'assets/research/zidao/photos/anyang/anyang-014.jpg',
      'assets/research/zidao/photos/anyang/anyang-015.jpg',
      'assets/research/zidao/photos/anyang/anyang-016.jpg',
      'assets/research/zidao/photos/anyang/anyang-017.jpg',
      'assets/research/zidao/photos/anyang/anyang-018.jpg',
      'assets/research/zidao/photos/anyang/anyang-019.jpg',
      'assets/research/zidao/photos/anyang/anyang-020.jpg',
      'assets/research/zidao/photos/anyang/anyang-021.jpg',
      'assets/research/zidao/photos/anyang/anyang-022.jpg',
      'assets/research/zidao/photos/anyang/anyang-023.jpg',
      'assets/research/zidao/photos/anyang/anyang-024.jpg',
      'assets/research/zidao/photos/anyang/anyang-025.jpg',
      'assets/research/zidao/photos/anyang/anyang-026.jpg',
      'assets/research/zidao/photos/anyang/anyang-027.jpg',
      'assets/research/zidao/photos/anyang/anyang-028.jpg',
      'assets/research/zidao/photos/anyang/anyang-029.jpg',
      'assets/research/zidao/photos/anyang/anyang-030.jpg',
      'assets/research/zidao/photos/anyang/anyang-031.jpg',
      'assets/research/zidao/photos/anyang/anyang-032.jpg',
      'assets/research/zidao/photos/anyang/anyang-033.jpg',
      'assets/research/zidao/photos/anyang/anyang-034.jpg',
      'assets/research/zidao/photos/anyang/anyang-035.jpg',
      'assets/research/zidao/photos/anyang/anyang-036.jpg',
      'assets/research/zidao/photos/anyang/anyang-037.jpg'
    ]
  },
  'nanjing': {
    label: 'China Station 02',
    title: 'Nanjing',
    images: [
      'assets/research/zidao/photos/nanjing/nanjing-001.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-002.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-003.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-004.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-005.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-006.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-007.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-008.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-009.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-010.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-011.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-012.jpg',
      'assets/research/zidao/photos/nanjing/nanjing-013.jpg'
    ]
  },
  'beijing': {
    label: 'China Station 03',
    title: 'Beijing',
    images: [
      'assets/research/zidao/photos/beijing/beijing-001.jpg',
      'assets/research/zidao/photos/beijing/beijing-002.jpg',
      'assets/research/zidao/photos/beijing/beijing-003.jpg',
      'assets/research/zidao/photos/beijing/beijing-004.jpg',
      'assets/research/zidao/photos/beijing/beijing-005.jpg',
      'assets/research/zidao/photos/beijing/beijing-006.jpg',
      'assets/research/zidao/photos/beijing/beijing-007.jpg',
      'assets/research/zidao/photos/beijing/beijing-008.jpg',
      'assets/research/zidao/photos/beijing/beijing-009.jpg',
      'assets/research/zidao/photos/beijing/beijing-010.jpg',
      'assets/research/zidao/photos/beijing/beijing-011.jpg',
      'assets/research/zidao/photos/beijing/beijing-012.jpg',
      'assets/research/zidao/photos/beijing/beijing-013.jpg',
      'assets/research/zidao/photos/beijing/beijing-014.jpg',
      'assets/research/zidao/photos/beijing/beijing-015.jpg',
      'assets/research/zidao/photos/beijing/beijing-016.jpg',
      'assets/research/zidao/photos/beijing/beijing-017.jpg',
      'assets/research/zidao/photos/beijing/beijing-018.jpg',
      'assets/research/zidao/photos/beijing/beijing-019.jpg',
      'assets/research/zidao/photos/beijing/beijing-020.jpg',
      'assets/research/zidao/photos/beijing/beijing-021.jpg',
      'assets/research/zidao/photos/beijing/beijing-022.jpg',
      'assets/research/zidao/photos/beijing/beijing-023.jpg',
      'assets/research/zidao/photos/beijing/beijing-024.jpg',
      'assets/research/zidao/photos/beijing/beijing-025.jpg',
      'assets/research/zidao/photos/beijing/beijing-026.jpg',
      'assets/research/zidao/photos/beijing/beijing-027.jpg',
      'assets/research/zidao/photos/beijing/beijing-028.jpg',
      'assets/research/zidao/photos/beijing/beijing-029.jpg',
      'assets/research/zidao/photos/beijing/beijing-030.jpg',
      'assets/research/zidao/photos/beijing/beijing-031.jpg',
      'assets/research/zidao/photos/beijing/beijing-032.jpg',
      'assets/research/zidao/photos/beijing/beijing-033.jpg',
      'assets/research/zidao/photos/beijing/beijing-034.jpg',
      'assets/research/zidao/photos/beijing/beijing-035.jpg',
      'assets/research/zidao/photos/beijing/beijing-036.jpg',
      'assets/research/zidao/photos/beijing/beijing-037.jpg',
      'assets/research/zidao/photos/beijing/beijing-038.jpg',
      'assets/research/zidao/photos/beijing/beijing-039.jpg',
      'assets/research/zidao/photos/beijing/beijing-040.jpg',
      'assets/research/zidao/photos/beijing/beijing-041.jpg',
      'assets/research/zidao/photos/beijing/beijing-042.jpg',
      'assets/research/zidao/photos/beijing/beijing-043.jpg',
      'assets/research/zidao/photos/beijing/beijing-044.jpg',
      'assets/research/zidao/photos/beijing/beijing-045.jpg',
      'assets/research/zidao/photos/beijing/beijing-046.jpg',
      'assets/research/zidao/photos/beijing/beijing-047.jpg',
      'assets/research/zidao/photos/beijing/beijing-048.jpg',
      'assets/research/zidao/photos/beijing/beijing-049.jpg',
      'assets/research/zidao/photos/beijing/beijing-050.jpg',
      'assets/research/zidao/photos/beijing/beijing-051.jpg',
      'assets/research/zidao/photos/beijing/beijing-052.jpg',
      'assets/research/zidao/photos/beijing/beijing-053.jpg',
      'assets/research/zidao/photos/beijing/beijing-054.jpg',
      'assets/research/zidao/photos/beijing/beijing-055.jpg',
      'assets/research/zidao/photos/beijing/beijing-056.jpg',
      'assets/research/zidao/photos/beijing/beijing-057.jpg',
      'assets/research/zidao/photos/beijing/beijing-058.jpg',
      'assets/research/zidao/photos/beijing/beijing-059.jpg',
      'assets/research/zidao/photos/beijing/beijing-060.jpg',
      'assets/research/zidao/photos/beijing/beijing-061.jpg',
      'assets/research/zidao/photos/beijing/beijing-062.jpg',
      'assets/research/zidao/photos/beijing/beijing-063.jpg',
      'assets/research/zidao/photos/beijing/beijing-064.jpg'
    ]
  },
  'ningbo': {
    label: 'China Station 04',
    title: 'Ningbo',
    images: [
      'assets/research/zidao/photos/ningbo/ningbo-001.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-002.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-003.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-004.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-005.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-006.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-007.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-008.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-009.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-010.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-011.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-012.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-013.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-014.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-015.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-016.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-017.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-018.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-019.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-020.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-021.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-022.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-023.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-024.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-025.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-026.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-027.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-028.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-029.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-030.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-031.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-032.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-033.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-034.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-035.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-036.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-037.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-038.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-039.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-040.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-041.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-042.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-043.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-044.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-045.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-046.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-047.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-048.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-049.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-050.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-051.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-052.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-053.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-054.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-055.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-056.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-057.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-058.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-059.jpg',
      'assets/research/zidao/photos/ningbo/ningbo-060.jpg'
    ]
  },
  'huzhou': {
    label: 'China Station 05',
    title: 'Huzhou',
    images: [
      'assets/research/zidao/photos/huzhou/huzhou-001.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-002.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-003.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-004.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-005.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-006.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-007.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-008.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-009.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-010.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-011.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-012.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-013.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-014.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-015.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-016.jpg',
      'assets/research/zidao/photos/huzhou/huzhou-017.jpg'
    ]
  },
  'qingdao': {
    label: 'China Station 06',
    title: 'Qingdao',
    images: [
      'assets/research/zidao/photos/qingdao/qingdao-001.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-002.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-003.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-004.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-005.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-006.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-007.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-008.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-009.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-010.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-011.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-012.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-013.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-014.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-015.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-016.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-017.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-018.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-019.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-020.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-021.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-022.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-023.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-024.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-025.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-026.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-027.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-028.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-029.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-030.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-031.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-032.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-033.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-034.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-035.jpg',
      'assets/research/zidao/photos/qingdao/qingdao-036.jpg'
    ]
  },
  'zhangzhou': {
    label: 'China Station 07',
    title: 'Zhangzhou / Xiamen University',
    images: [
      'assets/research/zidao/photos/zhangzhou/zhangzhou-001.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-002.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-003.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-004.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-005.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-006.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-007.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-008.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-009.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-010.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-011.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-012.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-013.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-014.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-015.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-016.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-017.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-018.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-019.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-020.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-021.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-022.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-023.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-024.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-025.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-026.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-027.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-028.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-029.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-030.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-031.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-032.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-033.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-034.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-035.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-036.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-037.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-038.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-039.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-040.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-041.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-042.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-043.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-044.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-045.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-046.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-047.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-048.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-049.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-050.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-051.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-052.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-053.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-054.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-055.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-056.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-057.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-058.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-059.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-060.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-061.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-062.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-063.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-064.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-065.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-066.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-067.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-068.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-069.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-070.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-071.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-072.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-073.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-074.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-075.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-076.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-077.jpg',
      'assets/research/zidao/photos/zhangzhou/zhangzhou-078.jpg'
    ]
  },
  'reading': {
    label: 'Overseas Station 01',
    title: 'University of Reading',
    images: [
      'assets/research/zidao/photos/reading/reading-001.jpg',
      'assets/research/zidao/photos/reading/reading-002.jpg',
      'assets/research/zidao/photos/reading/reading-003.jpg',
      'assets/research/zidao/photos/reading/reading-004.jpg',
      'assets/research/zidao/photos/reading/reading-005.jpg',
      'assets/research/zidao/photos/reading/reading-006.jpg',
      'assets/research/zidao/photos/reading/reading-007.jpg',
      'assets/research/zidao/photos/reading/reading-008.jpg',
      'assets/research/zidao/photos/reading/reading-009.jpg',
      'assets/research/zidao/photos/reading/reading-010.jpg',
      'assets/research/zidao/photos/reading/reading-011.jpg',
      'assets/research/zidao/photos/reading/reading-012.jpg',
      'assets/research/zidao/photos/reading/reading-013.jpg',
      'assets/research/zidao/photos/reading/reading-014.jpg',
      'assets/research/zidao/photos/reading/reading-015.jpg',
      'assets/research/zidao/photos/reading/reading-016.jpg',
      'assets/research/zidao/photos/reading/reading-017.jpg',
      'assets/research/zidao/photos/reading/reading-018.jpg',
      'assets/research/zidao/photos/reading/reading-019.jpg',
      'assets/research/zidao/photos/reading/reading-020.jpg',
      'assets/research/zidao/photos/reading/reading-021.jpg',
      'assets/research/zidao/photos/reading/reading-022.jpg',
      'assets/research/zidao/photos/reading/reading-023.jpg',
      'assets/research/zidao/photos/reading/reading-024.jpg',
      'assets/research/zidao/photos/reading/reading-025.jpg',
      'assets/research/zidao/photos/reading/reading-026.jpg',
      'assets/research/zidao/photos/reading/reading-027.jpg',
      'assets/research/zidao/photos/reading/reading-028.jpg',
      'assets/research/zidao/photos/reading/reading-029.jpg',
      'assets/research/zidao/photos/reading/reading-030.jpg',
      'assets/research/zidao/photos/reading/reading-031.jpg',
      'assets/research/zidao/photos/reading/reading-032.jpg',
      'assets/research/zidao/photos/reading/reading-033.jpg',
      'assets/research/zidao/photos/reading/reading-034.jpg',
      'assets/research/zidao/photos/reading/reading-035.jpg',
      'assets/research/zidao/photos/reading/reading-036.jpg',
      'assets/research/zidao/photos/reading/reading-037.jpg'
    ]
  },
  'south-africa': {
    label: 'Overseas Station 02',
    title: 'South Africa',
    images: [
      'assets/research/zidao/photos/south-africa/south-africa-001.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-002.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-003.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-004.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-005.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-006.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-007.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-008.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-009.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-010.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-011.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-012.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-013.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-014.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-015.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-016.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-017.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-018.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-019.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-020.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-021.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-022.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-023.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-024.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-025.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-026.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-027.jpg',
      'assets/research/zidao/photos/south-africa/south-africa-028.jpg'
    ]
  },
  'korea': {
    label: 'Overseas Station 03',
    title: 'Republic of Korea',
    images: [
      'assets/research/zidao/photos/korea/korea-001.jpg',
      'assets/research/zidao/photos/korea/korea-002.jpg',
      'assets/research/zidao/photos/korea/korea-003.jpg',
      'assets/research/zidao/photos/korea/korea-004.jpg',
      'assets/research/zidao/photos/korea/korea-005.jpg',
      'assets/research/zidao/photos/korea/korea-006.jpg',
      'assets/research/zidao/photos/korea/korea-007.jpg',
      'assets/research/zidao/photos/korea/korea-008.jpg',
      'assets/research/zidao/photos/korea/korea-009.jpg',
      'assets/research/zidao/photos/korea/korea-010.jpg',
      'assets/research/zidao/photos/korea/korea-011.jpg',
      'assets/research/zidao/photos/korea/korea-012.jpg',
      'assets/research/zidao/photos/korea/korea-013.jpg',
      'assets/research/zidao/photos/korea/korea-014.jpg',
      'assets/research/zidao/photos/korea/korea-015.jpg',
      'assets/research/zidao/photos/korea/korea-016.jpg'
    ]
  }
};

const params = new URLSearchParams(window.location.search);
const stationKey = params.get("station") || "anyang";
const station = stations[stationKey] || stations.anyang;

document.title = `${station.title} | Way of Type | CY Type`;
document.querySelector("[data-station-kind]").textContent = station.label;
document.querySelector("[data-station-title]").textContent = station.title;
document.querySelector("[data-station-summary]").textContent = `${station.images.length} exhibition images.`;

const wall = document.querySelector("[data-station-wall]");
station.images.forEach((src, index) => {
  const figure = document.createElement("figure");
  const image = document.createElement("img");
  image.src = src;
  image.alt = `${station.title} exhibition image ${index + 1}`;
  image.loading = "lazy";
  image.decoding = "async";
  figure.append(image);
  wall.append(figure);
});
